---
# tasks file for google-chrome
- name: Import Google Chrome's GPG key
  apt_key:
    url: "{{ google_chrome_gpg_key_url }}"
    state: present
  retries: 3
  delay: 5
  until: result is succeeded

- name: Add Google Chrome's repository
  apt_repository:
    repo: "{{ google_chrome_repo }}"
    state: present

- name: Update apt and install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes

- name: Ensure /etc/opt/chrome/policies/managed/ directory exists
  file:
    path: /etc/opt/chrome/policies/managed/
    state: directory
    mode: 0755

- name: Copy chrome-policies.json to target location
  copy:
    src: files/chrome-policies.json
    dest: /etc/opt/chrome/policies/managed/policies.json
    mode: 0644